# Generated by Django 5.0.6 on 2024-07-25 01:23

from django.db import migrations

def add_shelter_data(apps, schema_editor):
    Shelter = apps.get_model('Sotsuken_Portable', 'Shelter')
    Shelter.objects.create(
        management_id='HIROSHIMA-MINAMI-01',
        name='広島市南区役所',
        address='広島県広島市南区皆実町一丁目5番44号',
        latitude=34.379221,
        longitude=132.462482,
        max_capacity=500,
        current_occupancy=0,
        opening_status='open',
        is_pet_friendly=False,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('Sotsuken_Portable', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_shelter_data),
    ]
