"""
Django settings for Sotsuken_Portable_Project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9us3f5=%62u!r8_g8aaczg+(314l^%&-g&2l-btd7g(wm@1$l7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Sotsuken_Portable',
    #'Sotsuken_Portable.apps.SotsukenPortableConfig',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Sotsuken_Portable_Project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Sotsuken_Portable_Project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
     'default': {
        # 【変更点】mysql-connector-pythonを使用する場合のENGINEの指定
        'ENGINE': 'django.db.backends.mysql',

        # データベース名
        'NAME': 'sotsuken',

        # ユーザー名
        'USER': 'django_user',

        # パスワード
        'PASSWORD': 'your_password',

        # ホスト名
        'HOST': '127.0.0.1',

        # ポート番号
        'PORT': '3306',

        # オプション設定
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
            # 'autocommit': True, # 必要に応じて追加
        }
    }
}

# ----------------------------------------------------
# カスタムユーザーモデルの設定
# 形式: 'アプリ名.モデル名'
# ----------------------------------------------------
AUTH_USER_MODEL = 'Sotsuken_Portable.User'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ログイン成功後にリダイレクトするURL (ホーム画面を 'home' というURL名にすると仮定)
LOGIN_REDIRECT_URL = 'Sotsuken_Portable:index'

# ログアウト後のリダイレクト先
LOGOUT_REDIRECT_URL = 'Sotsuken_Portable:login'

# ログインが必要なページにアクセスした際にリダイレクトされるURL
LOGIN_URL = 'Sotsuken_Portable:login'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Google Maps APIキー
GOOGLE_MAPS_API_KEY = 'AIzaSyDGP_D8Wxg8EtuidVowg8xXeUA1h5f5Ntw'

# ASGI_APPLICATION の設定
ASGI_APPLICATION = 'Sotsuken_Portable_Project.asgi.application'

ASGI_THREADS = 1

# チャネルレイヤーの設定 (開発中はインメモリ、本番ではRedisを推奨)
CHANNEL_LAYERS = {
    "default": {
        # 開発中はこれでOK
        # "BACKEND": "channels.layers.InMemoryChannelLayer"
        # 本番環境にデプロイする際は、Redisを使うようにこちらを有効化する
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
